### ISSUE TITLE
sessionKey write to file fails

### ISSUE THREAD

**Issue by j-petit** [Sife-ops/dmenu_bw#1]
Hi, thanks for the great script!

On my machine (arch linux), the writing of the session key to the specified file fails if I unlock a session. I get the following error

`/usr/bin/dmenu_bw: line 65: /home/jp/.config/99-bitwarden.zsh: No such file or directory`

Line 65 in the script is 
`
65             printf 'export BW_SESSION="%s"' \
"$sessionKey" > "$sessionKeyFile"
`

Do you have any clue what could be the problem? My bash skills are fairly limited, but I cannot see an obvious error.

**Comment by Sife-ops** [comment]
Thank you for writing an issue and sorry about that, but I could not reproduce the problem. There have been updates to the dmenu_bw and dmenu_bw-git AUR packages. What does your config.json look like?

**Comment by j-petit** [comment]
I use `dmenu_bw-git r54.a1abf49-1` with the following config:
```
{
    "copyCmds": {
        "login": {
            ".login.username": [
                "echo \"$value\" | xclip -i -selection clipboard"
            ],
            ".login.password": [
                "echo \"$value\" | xclip -i -selection primary"
            ]
        },
        "securenote": {},
        "card": {},
        "identity": {}
    },
    "dmenuOpts": "-i -l 10",
    "editCmd": "st -e vim",
    "sessionKeyFile": "/home/jp/.config/99-bitwarden.zsh"
}
```

**Comment by Sife-ops** [comment]
I also now remember that if ```$XDG_CONFIG_HOME``` (which is not set by default on Arch) is not set, your config will not be read. Is your ```$XDG_CONFIG_HOME``` variable set in your environment?

**Comment by Sife-ops** [comment]
I just pushed an update to the dmenu_bw-git package that, if my theory is correct, fixes your problem. So, please get the latest version and tell me if that works.
