### ISSUE TITLE
notify-send slow when no notification daemon running

### ISSUE THREAD

**Issue by Smoolak** [Sife-ops/dmenu_bw#2]
Hi,

I would just like to report that when no notification daemon is running, notify-send will hang for a certain amount of time until a timeout is reached. This makes dmenu_bw hang for a long time before the password prompt is generated. To fix the issue the script can be modified to add "&" at the end of the notify-send calls to run them in the background in a non-blocking way.

**Comment by Sife-ops** [comment]
Thanks for the suggestion. I added the change to the dmenu_bw-git package in the AUR. Let me know if that fixes it for you.
