### ISSUE TITLE
Regeneration Of SessionKeyFile Token Each Time Dmenu_bw Runs From Dmenu/Rofi

### ISSUE THREAD

**Issue by M1ndo** [Sife-ops/dmenu_bw#4]
dmenu_bw doesn't read sessionKeyFile To check if BW_SESSION token does exist instead it overwrites the token and generates a new one this occurs when dmenu_bw is launched from dmenu/rofi because BW_SESSION doesn't exist in the env variables and it's not been launched from a terminal .

**Comment by Sife-ops** [comment]
You have to source your session key file in your startup profile for Xorg. If you have `"sessionKeyFile":"/home/foo/.cache/bwsession"` in your config.json, you have to put `source /home/foo/.cache/bwsession` in either your ~/.xprofile, or your ~/.xinitrc, depending on whether you use a display manager or startx, respectively.
